countries_dict = {
    'Afghanistan':'Asia',
    'Albania':'Europe',
    'Algeria':'Africa',
    'American Samoa':'Oceania',
    'Andorra':'Europe',
    'Angola':'Africa',
    'Anguilla':'North America',
    'Antigua and Barbuda':'North America',
    'Argentina':'South America',
    'Armenia':'Asia',
    'Aruba':'North America',
    'Australia':'Oceania',
    'Austria':'Europe',
    'Azerbaijan':'Asia',
    'Bahamas':'North America',
    'Bahrain':'Asia',
    'Bangladesh':'Asia',
    'Barbados':'North America',
    'Belarus':'Europe',
    'Belgium':'Europe',
    'Belize':'North America',
    'Benin':'Africa',
    'Bermuda':'North America',
    'Bhutan':'Asia',
    'Bolivia':'South America',
    'Bosnia and Herzegovina':'Europe',
    'Botswana':'Africa',
    'Brazil':'South America',
    'British Virgin Islands':'North America',
    'Brunei':'Asia',
    'Bulgaria':'Europe',
    'Burkina Faso':'Africa',
    'Burundi':'Africa',
    'Cambodia':'Asia',
    'Cameroon':'Africa',
    'Canada':'North America',
    'Cabo Verde':'Africa',
    'Cayman Islands':'North America',
    'Central African Republic':'Africa',
    'Chad':'Africa',
    'Chile':'South America',
    'China':'Asia',
    'Colombia':'South America',
    'Dominica':'North America',
    'Comoros':'Africa',
    'Congo (Brazzaville)':'Africa',
    'Congo (Kinshasa)':'Africa',
    'Cook Islands':'Oceania',
    'Costa Rica':'North America',
    'Croatia':'Europe',
    'Cuba':'North America',
    'Cyprus':'Asia',
    'Czechia':'Europe',
    'Denmark':'Europe',
    'Djibouti':'Africa',
    'Dominican Republic':'North America',
    'Timor-Leste':'Asia',
    'Ecuador':'South America',
    'Egypt':'Africa',
    'El Salvador':'North America',
    'Equatorial Guinea':'Africa',
    'Eritrea':'Africa',
    'Estonia':'Europe',
    'Ethiopia':'Africa',
    'Faeroe Islands':'Europe',
    'Falkland Islands':'South America',
    'Federated State of Micronesia':'Oceania',
    'Fiji':'Oceania',
    'Finland':'Europe',
    'France':'Europe',
    'French Guiana':'South America',
    'French Polynesia':'Oceania',
    'Gabon':'Africa',
    'Gambia':'Africa',
    'Georgia':'Asia',
    'Germany':'Europe',
    'Ghana':'Africa',
    'Gibraltar':'Europe',
    'Greece':'Europe',
    'Greenland':'North America',
    'Grenada':'North America',
    'Guadeloupe':'North America',
    'Guam':'Oceania',
    'Guatemala':'North America',
    'Guernsey':'Europe',
    'Guinea':'Africa',
    'Guinea-Bissau':'Africa',
    'Guyana':'South America',
    'Haiti':'North America',
    'Holy See':'Europe',
    'Honduras':'North America',
    'Hong Kong':'Asia',
    'Hungary':'Europe',
    'Iceland':'Europe',
    'India':'Asia',
    'Indonesia':'Asia',
    'Iran':'Asia',
    'Iraq':'Asia',
    'Ireland':'Europe',
    'Isle of Man':'Europe',
    'Israel':'Asia',
    'Italy':'Europe',
    'Cote d\'Ivoire':'Africa',
    'Jamaica':'North America',
    'Japan':'Asia',
    'Jersey':'Europe',
    'Jordan':'Asia',
    'Kazakhstan':'Asia',
    'Kenya':'Africa',
    'Kiribati':'Oceania',
    'Korea, South':'Asia',
    'Korea, Dem. People\'s Rep. of':'Asia',
    'Kuwait':'Asia',
    'Kyrgyzstan':'Asia',
    'Laos':'Asia',
    'Latvia':'Europe',
    'Lebanon':'Asia',
    'Lesotho':'Africa',
    'Liberia':'Africa',
    'Libya':'Africa',
    'Liechtenstein':'Europe',
    'Lithuania':'Europe',
    'Luxembourg':'Europe',
    'Macao':'Asia',
    'North Macedonia':'Europe',
    'Madagascar':'Africa',
    'Malawi':'Africa',
    'Malaysia':'Asia',
    'Maldives':'Asia',
    'Mali':'Africa',
    'Malta':'Europe',
    'Marshall Islands':'Oceania',
    'Martinique':'North America',
    'Mauritania':'Africa',
    'Mauritius':'Africa',
    'Mayotte':'Africa',
    'Mexico':'North America',
    'Monaco':'Europe',
    'Mongolia':'Asia',
    'Montserrat':'North America',
    'Morocco':'Africa',
    'Mozambique':'Africa',
    'Burma':'Asia',
    'Namibia':'Africa',
    'Nauru':'Oceania',
    'Nepal':'Asia',
    'Netherland Antilles':'North America',
    'Netherlands':'Europe',
    'New Caledonia':'Oceania',
    'New Zealand':'Oceania',
    'Nicaragua':'North America',
    'Niger':'Africa',
    'Nigeria':'Africa',
    'Niue':'Oceania',
    'Northern Mariana Islands':'Oceania',
    'Norway':'Europe',
    'Occupied Palestinian Territory':'Asia',
    'Oman':'Asia',
    'Pakistan':'Asia',
    'Palau':'Oceania',
    'Panama':'North America',
    'Papua New Guinea':'Oceania',
    'Paraguay':'South America',
    'Peru':'South America',
    'Philippines':'Asia',
    'Pitcairn':'Oceania',
    'Poland':'Europe',
    'Portugal':'Europe',
    'Puerto Rico':'North America',
    'Qatar':'Asia',
    'Moldova':'Europe',
    'Reunion':'Africa',
    'Romania':'Europe',
    'Russia':'Europe',
    'Rwanda':'Africa',
    'Saint Kitts and Nevis':'North America',
    'Saint Lucia':'North America',
    'San Marino':'Europe',
    'Sao Tome and Principe':'Africa',
    'Saudi Arabia':'Asia',
    'Senegal':'Africa',
    'Serbia':'Europe',
    'Seychelles':'Africa',
    'Sierra Leone':'Africa',
    'Singapore':'Asia',
    'Slovakia':'Europe',
    'Slovenia':'Europe',
    'Solomon Islands':'Oceania',
    'Somalia':'Africa',
    'South Africa':'Africa',
    'Spain':'Europe',
    'Sri Lanka':'Asia',
    'St. Helena':'Africa',
    'St. Vincent':'North America',
    'St-Pierre and Miquelon':'North America',
    'Sudan':'Africa',
    'Suriname':'South America',
    'Svalbard':'Europe',
    'Eswatini':'Africa',
    'Sweden':'Europe',
    'Switzerland':'Europe',
    'Syria':'Asia',
    'Taiwan*':'Asia',
    'Tajikistan':'Asia',
    'Thailand':'Asia',
    'Togo':'Africa',
    'Tonga':'Oceania',
    'Trinidad and Tobago':'North America',
    'Tunisia':'Africa',
    'Turkey':'Asia',
    'Turkmenistan':'Asia',
    'Turks and Caicos Islands':'North America',
    'Tuvalu':'Oceania',
    'Uganda':'Africa',
    'Ukraine':'Europe',
    'United Arab Emirates':'Asia',
    'United Kingdom':'Europe',
    'Tanzania':'Africa',
    'US':'North America',
    'United States Virgin Islands':'North America',
    'Uruguay':'South America',
    'Uzbekistan':'Asia',
    'Vanuatu':'Oceania',
    'Venezuela':'South America',
    'Vietnam':'Asia',
    'Wallis and Futuna':'Oceania',
    'Western Samoa':'Oceania',
    'Yemen':'Asia',
    'Zambia':'Africa',
    'Zimbabwe':'Africa',
    'Diamond Princess':'Other',
    'Kosovo':'Europe',
    'Montenegro':'Europe',
    'MS Zaandam':'Other',
    'Saint Vincent and the Grenadines':'North America',
    'South Sudan':'Africa',
    'Western Sahara':'Africa',
    'West Bank and Gaza':'Asia',
    }
